### ISSUE TITLE
Add items to model is not working

### ISSUE THREAD

**Issue by Kerhael** [ember-infinity/ember-infinity#270] opened 2018-03-29 13:51 UTC
Hi, 

We currently have an infinity model listings a collection of objects. We display this collection in a template with a button to duplicate selected items. Once "duplicate" button clicked, we want the template to be automatically updated with duplicated items.

Here is the route: 
```
model(params) {
  let queryParams = Ember.$.extend({}, params, { perPage: 100, startingPage: 1 });
  return this.infinityModel("obj", queryParams); 
}
```

Then in the template, we loop on this model to display the objects in a table, with cheboxes and a button to duplicate checked items: 
```
{{async-button action=(action "duplicate") default="Duplicate" pending="Duplicating..." class="btn btn-success" disableWhen=emptyBulk}}
<table>
  <tbody>
    {{#each model as |obj|}}
      {{obj.name}}
      <input type="checkbox" ...>
    {{/each}}
  </tbody>
</table>
```

In our controller:
```
 duplicate() {
  let url = '/duplicate';
  return this.get('ajax').post(url, {
    contentType: 'application/json; charset=utf-8',
    data: JSON.stringify({ids: this.get('objIDs')})
  }).then((data) => {
    // data.obj is an array with duplicated objects
    this.get('model').pushObjects(data.objs);
    this.get('notifications').success('Objects duplicated');
  }).catch((error) => {
    this.get('notifications').error(errorMsg(error));
  });
}
```
With ObjIDs being an array of checked objects' IDs.

We get the following error: *internalModel.getRecord is not a function*

We've tried it all (at least all we could think about) with:
- this.get('store').pushPayload(data.objs)
- this.get('model').addObjects(data.objs)
- loop on data.objs then pushObject or pushPayload or add Object or create new ember record and push it

Nothing is working, at best with have no error but the model (i.e. the template) is never updated.

Would you have any suggestion on how we should do this?

Thanks a lot,
Kind regards

**Comment by snewcomer** [comment] 2018-03-29 15:19
So `model` is an ember data array and what you are trying to push in is an array of objects with ids?  I think when you call `pushObjects`, you might need instances of an Ember Data class.  Also see this discussion if I got something wrong.  

See this discussion: https://github.com/emberjs/data/issues/3530

**Comment by Kerhael** [comment] 2018-03-30 13:21
Hi @snewcomer,

Thanks for your answer.
We tried it all but nothing would work, seemingly because the infinity model we have is an immutable array.

We ended up creating a refresh function in *routes/application.js*: 
```
    refreshRoute: function() {
      this.refresh();
    }
```

And call it from the controller: 
```
this.send("refreshRoute");
```
There has to be a better way but for now this is all we could find.

**Comment by snewcomer** [comment] 2018-03-30 14:18
@Kerhael I think this might be an Ember problem.  However, I would need a bit more clarity on my last comment to help more.  

The InfinityModel is simply just an ArrayProxy, so it is possible to `pushObjects`.  This is what we do when we request the next page here: https://github.com/ember-infinity/ember-infinity/blob/master/addon/mixins/route.js#L364

Also, I added this issue last night - https://github.com/ember-infinity/ember-infinity/issues/272

**Comment by bryanhickerson** [comment] 2018-04-01 23:00
I think ember 3.0 broke this, I get an immutability error after upgrading when loading the next page (or manually adding or removing an element from the infinityModel). This might be the cause: https://github.com/emberjs/ember.js/pull/16157/files. You can sidestep the issue by updating the content property on the ArrayProxy directly. For example: `messages.addObject(message)` -> `messages.content.addObject(message._internalModel)`. This doesn't help the case of the error being thrown in `_doUpdate`, I was considering extending InfinityModel and overriding `addObject`, but I guess I'd have to override `pushObjects` and `unshiftObjects` as well. I could just file an issue with ember, I'm unsure if this is something they want to support, but maybe they would be sympathetic since it's an unexpected regression.

**Comment by bryanhickerson** [comment] 2018-04-02 00:18
Filed an upstream issue: https://github.com/emberjs/ember.js/issues/16451

**Comment by snewcomer** [comment] 2018-04-02 04:17
@bryanhickerson @Kerhael Awesome!  Really appreciate everyone bringing up this issue.  👍 

Curious - Could you paste what code is leading to this error?  I still can't reproduce on my project nor on the demo app.  Did you try upgrading to `3.1.0-beta.5`?  I'm seeing that this commit added `pushObjects` as a method on the array mixin... 

https://github.com/emberjs/ember.js/commit/66a1dc337fb4d48a4f378070226fce67b0f9156b#diff-cc5d23e161123b9dbf17e00337b75448R1535

**Comment by snewcomer** [comment] 2018-04-02 04:28
I'm further wondering if, at some point throughout the lifecycle of the app,`content` does not implement `Array` or `MutableArray` anymore.  Just throwing a thought out there :)

https://github.com/emberjs/ember.js/blob/master/packages/ember-runtime/lib/system/array_proxy.js#L97

**Comment by bryanhickerson** [comment] 2018-04-02 04:50
I’ll try out the ember 3.1 beta and let you know.

**Comment by snewcomer** [comment] 2018-04-02 04:53
Sry forgot to ask- What version of ember-infinity are you on?  Master of this lib + Ember beta would give us a good clue.

**Comment by bryanhickerson** [comment] 2018-04-02 04:57
I’m on 0.2.8.

**Comment by bryanhickerson** [comment] 2018-04-02 05:06
There was an update to my ember issue that explains what is happening
https://github.com/emberjs/ember.js/issues/16451

**Comment by snewcomer** [comment] 2018-04-02 13:45
@bryanhickerson Great digging.  Just to point out, on `1.0.0-beta.1`, we are using `toArray` to update the

**Comment by snewcomer** [comment] 2018-04-02 13:47
@bryanhickerson Great digging.  You might be already aware, but just to point out, on `1.0.0-beta.1`, we are using `toArray()` to update the collection when a new response comes back.

https://github.com/ember-infinity/ember-infinity/blob/master/addon/mixins/route.js#L364

**Comment by bryanhickerson** [comment] 2018-04-02 14:48
@snewcomer Looks like upgrading does fix the issue with loading additional pages. I'm seeing some other breakage due to 1.0 changes, but it's good to know that we'll be able to get past this issue once we can upgrade to ember-infinity 1.0.

**Comment by snewcomer** [comment] 2018-04-02 14:59
@Kerhael ☝️ 

@bryanhickerson Great!  Yeah 1.0 is significantly faster (uses IntersectionObserver) for large lists and greatly improves the organization of the codebase.  Lmk if there are any other breakages that I can help with.  The upgrade to 1.0 shouldn't be too painful (the API's are pretty much the same).  Also, the README should be up to date.

**Comment by Kerhael** [comment] 2018-04-04 07:32
@snewcomer @bryanhickerson sry I was away for easter holidays.
I just tried `1.0.0-beta.1` and the collection is well updated 😄.
Thanks a lot for your help!

**Comment by snewcomer** [comment] 2018-04-15 18:40
#271 was merged.  See the README for some updates.  Lmk what everyone thinks!  Will close this for now.

**Closed by snewcomer** 2018-04-15 18:40 UTC
